// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqkNUqDHN-0cxuw-He-ndOWGexLwpqSCk',
    appId: '1:269933221255:web:3025910038a1e91096af22',
    messagingSenderId: '269933221255',
    projectId: 'chatcoapp-a87e3',
    authDomain: 'chatcoapp-a87e3.firebaseapp.com',
    storageBucket: 'chatcoapp-a87e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGyJD9MZKRBvg2G25QwvTL2Xl1L9EtM-s',
    appId: '1:269933221255:android:00ed5092461c70a096af22',
    messagingSenderId: '269933221255',
    projectId: 'chatcoapp-a87e3',
    storageBucket: 'chatcoapp-a87e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDwcWQ-akDpgJ2n9f1x__y4jJopNipRG4',
    appId: '1:269933221255:ios:90d207b9e4a4a91296af22',
    messagingSenderId: '269933221255',
    projectId: 'chatcoapp-a87e3',
    storageBucket: 'chatcoapp-a87e3.appspot.com',
    iosClientId: '269933221255-jtls4324qb5457ri6lpbrkg0bdanr8u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatcoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDwcWQ-akDpgJ2n9f1x__y4jJopNipRG4',
    appId: '1:269933221255:ios:90d207b9e4a4a91296af22',
    messagingSenderId: '269933221255',
    projectId: 'chatcoapp-a87e3',
    storageBucket: 'chatcoapp-a87e3.appspot.com',
    iosClientId: '269933221255-jtls4324qb5457ri6lpbrkg0bdanr8u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatcoApp',
  );
}
